name: Terraform CD (Dev)

on:
  push:
    branches:
      - main
    paths:
      - 'environments/dev/**'

permissions:
  contents: read
  id-token: write   # Required for OIDC

concurrency:
  group: terraform-cd-dev
  cancel-in-progress: false

env:
  WORKING_DIR: environments/dev
  TERRAFORM_VERSION: 1.14.0
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: "938108731356"

jobs:
  deploy:
    name: Plan & Apply (Dev)
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout infra repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      # 3️⃣ Authenticate to AWS via OIDC
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/github-actions-role-global
          aws-region: ${{ env.AWS_REGION }}

      # 4️⃣ Terraform Init (REAL backend)
      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      # 5️⃣ Terraform Plan (saved)
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ${{ env.WORKING_DIR }}
        env:
          TF_VAR_api_shared_secret: ${{ secrets.API_SHARED_SECRET }}

      # 6️⃣ Terraform Apply (exact plan)
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.WORKING_DIR }}
        env:
          TF_VAR_api_shared_secret: ${{ secrets.API_SHARED_SECRET }}
